### ISSUE TITLE
MsBuildTaskFactory - native assemblies

### ISSUE THREAD

**Issue by dazinator** [stazz/UtilPack#14]
The good news is that this is an open source project, so you should be able to checkout and replicate this issue if you need to.

It's here: https://github.com/dazinator/GitVersion/tree/feature/netstandard which is part of an active PR.
(PR is here: https://github.com/GitTools/GitVersion/pull/1269)

The solution has a project called `GitVersionTask` which is the msbuild task. I have updated it to use `UtilPack`'s wonderful msbuild task factory. The issue seems to be that one of the dependencies - called libgit2sharp, has some native libraries. When I build a project with the task I get this:

```

Using "GetVersion" task from the task factory "NuGetTaskRunnerFactory".
1>  Task "GetVersion"
1>    Resolved GitVersionTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null located in C:\Users\Darrell\.nuget\packages\gitversiontask\4.0.0-alpha0001\build\net461\GitVersionTask.dll and loaded from C:\Users\Darrell\.nuget\packages\gitversiontask\4.0.0-alpha0001\build\net461\GitVersionTask.dll.
1>    Resolved Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a located in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.Utilities.Core.dll and loaded from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.Utilities.Core.dll.
1>    Resolved Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a located in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll and loaded from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll.
1>    Resolved GitVersionCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null located in C:\Users\Darrell\.nuget\packages\gitversioncore\1.0.0\lib\net40\GitVersionCore.dll and loaded from C:\Users\Darrell\.nuget\packages\gitversioncore\1.0.0\lib\net40\GitVersionCore.dll.
1>    Resolved Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a located in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.dll and loaded from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.dll.
1>    Resolved Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a located in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.dll and loaded from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.dll.
1>    Resolved Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a located in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll and loaded from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll.
1>    Resolved GitTools.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null located in C:\Users\Darrell\.nuget\packages\gittools.core\1.3.1\lib\net45\GitTools.Core.dll and loaded from C:\Users\Darrell\.nuget\packages\gittools.core\1.3.1\lib\net45\GitTools.Core.dll.
1>    Resolved LibGit2Sharp, Version=0.25.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333 located in C:\Users\Darrell\.nuget\packages\libgit2sharp\0.25.0-preview-0033\lib\net40\LibGit2Sharp.dll and loaded from C:\Users\Darrell\.nuget\packages\libgit2sharp\0.25.0-preview-0033\lib\net40\LibGit2Sharp.dll.
1>    MSBUILD : warning : WARN [10/24/17 19:11:27:28] Could not determine assembly version: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
1>    MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
1>    MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.LoadNativeLibrary()
1>    MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods..cctor()
1>    MSBUILD : warning :    --- End of inner exception stack trace ---
1>    MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.git_buf_free(GitBuf buf)
1>    MSBUILD : warning :    at LibGit2Sharp.Core.Handles.GitBuf.Dispose()
1>    MSBUILD : warning :    at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
1>    MSBUILD : warning :    at LibGit2Sharp.Core.Proxy.git_repository_discover(FilePath start_path)
1>    MSBUILD : warning :    at LibGit2Sharp.Repository.Discover(String startingPath)
1>    MSBUILD : warning :    at GitVersion.GitPreparer.GetDotGitDirectory()
1>    MSBUILD : warning :    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache)
1>    MSBUILD : warning :    at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)
1>  Done executing task "GetVersion".
1>Done building target "GetVersion" in project "ClassLibrary6.csproj".

```

I can see it ends up resolving `LibGit2Sharp`. This nuget package depends on `LibGit2Sharp.NativeBinaries` package - which looks like this:

![image](https://user-images.githubusercontent.com/3176632/31960956-416fa282-b8f1-11e7-8070-1a0e137c0259.png)

Note, this package has the native binaries in it, under a "runtimes" folder and it also *includes build files* so that when you build your project, those native assemblies end up in `lib` folder in your output folder.

So I tried copying the `lib` folder containing the native directories into my nuget package containing my task - but I still get the same problem that they cannot be located. 

I am not quite sure how to resolve this one. Any ideas?

**Comment by dazinator** [comment]
It looks like the `libgit2sharp` assembly looks for its native assemblies like so:

https://github.com/libgit2/libgit2sharp/blob/72fa36811899a7db28e41a660b0b62ad4993d1f9/LibGit2Sharp/GlobalSettings.cs#L33


Which seems to be using the location of the `libgit2sharp` assembly. In the normal case this would be in your applications bin folder. However because I am using `UtilPack` the libgit2sharp assembly is being resolved from seperate nuget package location.

Not quite sure how best to solve this. I think I will need to remove `libgit2sharp` from my nuspec file, and include the `libgit2sharp` assembly, and its native assemblies in my tasks nuget pacakge. I will give this a try.

**Comment by dazinator** [comment]
I have raised a more specific issue relating to this here: https://github.com/libgit2/libgit2sharp/issues/1498
I am not sure if UtilPack is actually to blame, I think it might be down to how libgit2sharp resolves its native libs.

**Comment by dazinator** [comment]
Something I have noticed. Nerdbannk.gitversion handles loading unmanaged assemblies by overriding a method on the AssemblyLoadContext which can be seen here:

https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/MSBuildExtensionTask/ContextAwareTask.cs#L92

Each task then provides its own directory where the unmanaged assemblies should be located.  I wonder if utilpack taskfactory could do something similar.

Utilpack may even have enough information to be able to find the unmanaged assembly a different way - like looking in the "runtimes" area in the nuget package or looking for .deps files or some other mechanism

**Comment by stazz** [comment]
I took alook at issues and comments, and indeed your PR looks like a valid solution to me. Let me know if something needs to be done to UtilPack after all. :) 

Btw, I would recommend using `CodeBase` instead of `Location` for assembly, as `Location` will be something different (on .NET Desktop runtime) when using [shadow copying](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/shadow-copy-assemblies) . I know at least Microsoft Office uses shadow copying for its add-ins, and I suspect some other host applications will utilize that technology.

> like looking in the "runtimes" area in the nuget package

That is a good idea. Basically the whole topic of unmanaged DLLs is completely untouched by UtilPack, as there was no need for it so far. I guess I better start working on that too. :)

**Comment by dazinator** [comment]
Yeah I dont think my PR will be accepted :-(
I think Libgit2sharp - when it tries to load the native assembly, it may trigger that resolve method on the util pack assembly load context? So it could potentially be addressed by utilpack? Thing is.. how does utilpack know where to look.. i.e should it look in the task assembly location, the tasks nuget package (runtimes folder), or try and find a seperate nuget package containing the native library and look for a runtimes folder in there.. Perhaps you already have some thoughts on that!

**Comment by stazz** [comment]
> Yeah I dont think my PR will be accepted :-(

Pity, why is that? They don't want to break existing logic?

> Perhaps you already have some thoughts on that!

Not much, apart from doing ugly business of crawling through stack trace to see which assembly initiated the call. All I really need is the `AssemblyName` of the caller looking for unmanaged assembly - I can then use that information to deduce its location and thus will know where to look for the unmanaged assembly.

I'll need to put on my thinking cap once again when I start working on these issues. Currently I am blocked with a stuff related to my CBAM repository, but once that is done, I'll probably fix all currently open issues. :)

**Comment by dazinator** [comment]
> Pity, why is that? They don't want to break existing logic?

No, I think I agree now that it isn't the right solution.
Basically, all they do, is if they are running on Windows, they set the `PATH` environment variable to include the folder location of the native assemblies. Then when they do a ` [DllImport(libgit2)]` - the binaries are found. My PR changes this on Windows, so that NETCORE and DESKTOP both add the same value to PATH. This does work.. on windows only. Because Linux etc doesn't use environment variables when resolving the assemblies for a  [DllImport(libgit2)] then my change wouldn't fix it on those OS's.

I think the only place you can handle this problem consistently, irrespective of platform, is in a Custom Assembly Load Context for the task. The default Assembly Load Context (the one that MsBuild is aware of) is not going to be able to resolve native assemblies outside of the application's base path (i.e the MSBUILD,EXE location) if I am not mistaken. I believe the concept of `deps` files should allow that to happen but I am not sure if MsBuild honours them when loading task assemblies.

> I'll need to put on my thinking cap once again when I start working on these issues. Currently I am blocked with a stuff related to my CBAM repository, but once that is done, I'll probably fix all currently open issues. :)

No problemo! Thanks for your hardwork so far!

**Comment by stazz** [comment]
> No problemo! Thanks for your hardwork so far!

You're welcome - it has been nice to see that someone is actually using stuff I've done! :) And thanks for the patience with all the bugs and issues you've discovered!

A quick update: I've just pushed 0.4.0 release of CBAM stuff, and I'll start working on this and other open issues in UtilPack tomorrow!

**Comment by stazz** [comment]
This has been fixed for version `2.1.0`, which I've just uploaded to NuGet. In best case scenario, no any further configuration is needed - things should just work. But if they don't, check out `NuGetPlatformRID` task parameter in [README](https://github.com/CometaSolutions/UtilPack/tree/develop/Source/UtilPack.NuGet.MSBuild). :)

**Comment by dazinator** [comment]
Awesome, I can't wait to give this a go!

**Comment by stazz** [comment]
If you're having problems with native assemblies on *nix system (hint: on detailed verbosity, task factory prints the process NuGet framework and platform RID), you might wanna try `2.1.1` version which I've just pushed. I realized too late I had a little discrepancies related to automatic NuGet RID detection. I couldn't find anything in official NuGet packages so I just needed to write my own, but I noticed few bugs soon after `2.1.0` release.

**Comment by dazinator** [comment]
Ok, I will onyl be able to test on Windows unfortuantely, but hopefully I'll be able to get others to test `GitVersion` on other platforms and we will see how it goes!

**Comment by stazz** [comment]
Okies - I only tested on Windows myself too, hehe. :) Let's see how it goes on other operating systems! Edit: I've fixed Windows-related bug in `2.1.1` too, but it would only manifest itself on Win8.1.

**Comment by bording** [comment]
Are either of you using Windows 10? It's really easy to test linux stuff now that WSL is baked into Windows.

**Comment by stazz** [comment]
@bording I am on Win10 - can you give instructions (or link to instructions) so I can perform the tests? :)

Edit: Nvm - I think I got it, installing it now. Will let you know how the tests go.

**Comment by stazz** [comment]
Update: I get it to work now (but there was one thing I had to do, so a new release will be required), *BUT* the DLL in `LibGit2Sharp` version `0.24.0` has `git2-15e1193` module reference, while the file in `libgit2sharp.nativebinaries\1.0.185\runtimes\linux-x64\native` folder is named `libgit2-15e1193.so`. There is a `libgit2sharp.nativebinaries\1.0.185\libgit2\LibGit2Sharp.dll.config` file, but it has redirect to `lib/linux/x86_64/libgit2-15e1193.so`, which is a bit weird as it is not present in the package.

In any case, the `.so` file is now detected in Linux environment.

Is file naming strategy changing for `0.25.0` release? Is there some reason why the Windows native DLL file in `LibGit2Sharp.NativeBinaries` is named differently than other native DLLs? Just wanting to know so that if there are any special cases, this task factory can be prepared for them (BEFORE I make a new release again).

**Comment by bording** [comment]
@stazz Both the 0.24.0 and the current prerelease of 0.25.0 are referencing the same native binaries package, though that will be changing for newer 0.25.0 prereleases.

The LibGit2Sharp.dll.config is only for mono support, so that file can be completely disregarded for .NET Core. 

The standard runtimes/ folder is where .NET Core will be looking for the correct binary based on the RID lookup mechanism. In the future to I do plan on tweaking the actual binaries shipped to handle more linux distros, so the exact set of RID folder may change over time, but it will still follow the standard for native libraries in a NuGet package.

As for the actual difference in filenames, that's simply how native libraries work on non-windows platforms. If you have a `[DllImport("git2-15e1193")]` in your code, on Windows it will be looking for `git2-15e1193.dll`. On linux that same attribute will cause it to go looking for `libgit2-15e1193.so`, and on macOS it will look for `libgit2-15e1193.dylib`.

**Comment by stazz** [comment]
> The LibGit2Sharp.dll.config is only for mono support, so that file can be completely disregarded for .NET Core.

Okay, thanks for the heads-up!

> As for the actual difference in filenames, that's simply how native libraries work on non-windows platforms.

Ah, seems there is some hint to this in discussion of dotnet/coreclr#930 . I've never needed native libraries myself, so I had no idea about this. Not particularly nice feature, IMO, but we live in an imperfect world, so just got to live with this. :)

In any case, I'll make appropriate changes so that libraries with "lib" prefix will also be searched on non-windows platforms. Perhaps also make this fully customizable as task parameter with referenced-name-to-actual-name mapping.

**Comment by stazz** [comment]
I've released the `2.2.0` version of `UtilPack.NuGet.MSBuild`. The native assembly resolving now has been tested to work in both Windows 10 and WSL (Ubuntu 16.04). More advanced runtime detections (special flavors of Linux) are not yet supported by automatic runtime detection, but can be specified explicitly.

I've also added `UnmanagedAssemblyReferenceMap` task factory parameter, which is explained in [README](https://github.com/CometaSolutions/UtilPack/tree/develop/Source/UtilPack.NuGet.MSBuild).

Let me know if there are still troubles with unmanaged assemblies!

**Comment by dazinator** [comment]
I just gave `2.2.0` a go. Desktop msbuild still working fine. `dotnet build` failed trying to resolve the native assembly - I assume this must be something I am doing wrong so I will read the README and double check everything:

```

 Using "GetVersion" task from the task factory "NuGetTaskRunnerFactory".
       Task "GetVersion"
         Resolved GitVersionTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null located in C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha-0001\build\netstandard1.5\GitVersionTask.dll and loaded from C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha-0001\build\netstandard1.5\GitVersionTask.dll.
         Resolved GitVersionCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null located in C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha-0001\build\netstandard1.5\GitVersionCore.dll and loaded from C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha-0001\build\netstandard1.5\GitVersionCore.dll.
         Resolved GitTools.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null located in C:\Users\Darrell\.nuget\packages\gittools.core\1.3.1\lib\netstandard1.3\GitTools.Core.dll and loaded from C:\Users\Darrell\.nuget\packages\gittools.core\1.3.1\lib\netstandard1.3\GitTools.Core.dll.
         Resolved LibGit2Sharp, Version=0.25.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333 located in C:\Users\Darrell\.nuget\packages\libgit2sharp\0.25.0-preview-0033\lib\netstandard1.3\LibGit2Sharp.dll and loaded from C:\Users\Darrell\.nuget\packages\libgit2sharp\0.25.0-preview-0033\lib\netstandard1.3\LibGit2Sharp.dll.
     1>MSBUILD : warning : WARN [10/31/17 22:53:30:34] Could not determine assembly version: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': The specified module could not be found. (Exception from HRESULT: 0x8007007E)\r [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()\r [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.LoadNativeLibrary()\r [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods..cctor()\r [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
MSBUILD : warning :    --- End of inner exception stack trace ---\r [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.git_buf_free(GitBuf buf)\r [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)\r [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
MSBUILD : warning :    at LibGit2Sharp.Repository.Discover(String startingPath)\r [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
MSBUILD : warning :    at GitVersion.GitPreparer.GetDotGitDirectory() in C:\Users\Darrell\Source\Repos\GitVersion\src\GitVersionCore\GitPreparer.cs:line 139\r [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
MSBUILD : warning :    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache) in C:\Users\Darrell\Source\Repos\GitVersion\src\GitVersionCore\ExecuteCore.cs:line 32\r [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
MSBUILD : warning :    at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication) in C:\Users\Darrell\Source\Repos\GitVersion\src\GitVersionCore\ExecuteCore.cs:line 81 [C:\Users\Darrell\Documents\Visual Studio 2017\Projects\ClassLibrary8\ClassLibrary8.csproj]
       Done executing task "GetVersion".
```

**Comment by stazz** [comment]
Hmm, are the newest versions (`0.25.0-preview-0033` of LibGit2Sharp and whatever version of LibGit2Sharp.NativeLibraries) available somewhere online? Maybe they differ in some sublte way from the ones I was testing. Can you tell what the task factory is printing right before restore (probably will need detailed verbosity)? It should look like this `Detected current NuGet framework to be ".NETCoreApp,Version=v2.0", with RID "win10-x64", and local repositories: <homedir>\.nuget\packages\.`.

**Comment by dazinator** [comment]
I don't see that line..

Here is the full output of `dotnet build -v detailed`: https://gist.github.com/dazinator/971f49b99ce15c9bc6a81407018c05de

**Comment by dazinator** [comment]
And here is the nuget package containing the task (changed extension to .zip)
[GitVersionTask.0.0.1-alpha-0001.zip](https://github.com/CometaSolutions/UtilPack/files/1432612/GitVersionTask.0.0.1-alpha-0001.zip)

**Comment by dazinator** [comment]
oh wait..

this might be to blame!

```
<UtilPackNuGetMSBuildPropsPath Condition=" '$(UtilPackNuGetMSBuildPropsPath)' == ''">$(MSBuildThisFileDirectory)../../../utilpack.nuget.msbuild/2.0.0/build/UtilPack.NuGet.MSBuild.props</UtilPackNuGetMSBuildPropsPath>

```

**Comment by dazinator** [comment]
SUCCESS! :-). After updating the UtilPack nuget package to version `2.2.0` I had forgotten to also change `UtilPackNuGetMSBuildPropsPath`. Once I changed that to match, it works like a charm.

**Comment by stazz** [comment]
> Here is the full output of dotnet build -v detailed: https://gist.github.com/dazinator/971f49b99ce15c9bc6a81407018c05de

It seems you are using the old version: `Initializing task factory "UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory" from assembly "C:\Users\Darrell\.nuget\packages\utilpack.nuget.msbuild\2.0.0\build\\netcoreapp1.1\UtilPack.NuGet.MSBuild.dll".` You probably didn't update the `Functionality.targets` file? It's a pity the version is hardcoded there and has to be separately maintained, but I can't figure any better way to handle it right now at least.

> And here is the nuget package containing the task (changed extension to .zip)
GitVersionTask.0.0.1-alpha-0001.zip

Ouch, looks like this one has non-standard folder structure, with native libraries residing in `build/<framework>/lib` structure, which also has non-standard naming conventions of `win32`. The `Lib2GitSharp.NativeBinaries` package has the standard-conforming directories, with `runtime` folder containing properly-named native directory folders.

Anyway, you can handle this situation using the `UnmanagedAssemblyReferenceMap`, __EXCEPT__ that it requires the native assemblies to be "seen" by NuGet restore command - which I am not sure if it does, considering that unusual folder structure.

I'll do better error reporting and see what I can do for `UnmanagedAssemblyReferenceMap` handling tomorrow - right now it's getting late and I need to catch some sleep. Thanks for providing samples though, it really helped moving this issue forward once again! :)

**Comment by dazinator** [comment]
Yeah I wouldnt worry about looking into this any further as it all seems to be working nicely now once updated that msbuild prop to use 2.2.0 props file.

That 'lib' folder you have seen in the nuget package only needs to be there for `.Net Desktop`, because in that case LibGit2sharp sets PATH to that location and it seems to work. On `.Net Core`, it looks like the util pack task factory resolves the native binaries from their proper nuget package location now, and so it looks like I dont need to include a `lib` folder in the task package for netstandard at all.

Sweeet.

**Comment by stazz** [comment]
> so it looks like I dont need to include a lib folder in the task package for netstandard at all.

Glad to hear! So I guess the native dependencies are still bundled via Git2Sharp.NativeLibraries package, which will make the NuGet restore command "see" them, and all works out.

I'll still make a little better error reporting, and while I was falling asleep I realized that there is most likely a bug which will manifest itself when the application references more than one native assembly. I'll sort those things out for `2.2.1`. :)
