### ISSUE TITLE
usage of UtilPack.MSBuild.AsyncExec

### ISSUE THREAD

**Issue by badcodelab** [stazz/UtilPack#18]
Hi,
How can I import and use your custom task? Could you provide a working example?
I'm getting an error
"The task factory "UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory" could not be loaded from the assembly "$(SolutionDir)packages\UtilPack.NuGet.MSBuild.2.3.0\build\net45\UtilPack.NuGet.MSBuild.dll"
win10, vs2017

**Comment by stazz** [comment]
Hi,

It seems you are opening legacy VS project, as the NuGet package folder is `$(SolutionDir)packages`. Do you get any more detailed error message? There were some problems with this kind of setup, but I fixed #13 sometime ago, and it should be working fine. But perhaps some new VS update changed something and broke things.

I'll try to see to reproduce this error during this weekend with just blank legacy project, but any more detailed error message would help a lot. :)

**Comment by stazz** [comment]
I've confirmed to have a working example as follows:

```xml
  <UsingTask
     Condition=" '$(UtilPackNuGetMSBuildAssemblyPath)' != '' "
     TaskFactory="UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory"
     AssemblyFile="$(UtilPackNuGetMSBuildAssemblyPath)"
     TaskName="UtilPack.MSBuild.AsyncExec.AsyncExecTask">
    <Task>
      <NuGetTaskInfo>
        <PackageID>UtilPack.MSBuild.AsyncExec</PackageID>
      </NuGetTaskInfo>
    </Task>
  </UsingTask>

   <Target Name="AfterBuild">
    <UtilPack.MSBuild.AsyncExec.AsyncExecTask
        Command="path/to/executable" />
  </Target>
```

Does this help with your issue, are you able to use `UtilPack.MSBuild.AsyncExec.AsyncExecTask` with these instructions?

**Comment by badcodelab** [comment]
@stazz thank you! I didn't put any inner tags because I didn't find such example. So I moved to similar task from MSBuild.ExtensionPack.
I'll try it later. Does your task support ConsoleToMSBuild, WorkingDirectory or Condition parameters?

**Comment by stazz** [comment]
> Does your task support ConsoleToMSBuild, WorkingDirectory or Condition parameters?

The `UtilPack.MSBuild.AsyncExec.AsyncExecTask` task extends `Microsoft.Build.Tasks.Exec`, and thus supports some of the features. The `Condition` and `WorkingDirectory` are supported. However, `ConsoleToMSBuild` is not currently supported, because the MSBuild process might terminate before the child process does, since the AsyncExecTask does not wait for the child process to terminate.
