### ISSUE TITLE
Make UtilPack NuGet process framework autodetection .NET Core 2.1 -aware

### ISSUE THREAD

**Issue by stazz** [stazz/UtilPack#27]
What title says. The .NET Core 2.1 was recently released, and one needs to add auto-detection code for it in relevant UtilPack NuGet project.

**Comment by dazinator** [comment]
Do you think this could explain the following error I am seeing?
   
    Build started 24/07/2018 02:02:26.
    Target Hook_DnnVsProjectPreBuild:

    Target DnnVsProjectPreBuild:

      Detected current NuGet framework to be ".NETFramework,Version=v4.6.1", with RID "win10-x86", and local repositories: C:\Users\darre\.nuget\packages\.

      [NuGet Minimal]: Restoring packages for C:\Users\darre\.nuget\packages\dnnvsprojectsystem.buildtools\0.0.1-alpha0000\build\functionality\Functionality.targets...

      MSBUILD : Task factory error NMSBT001: Exception in initialization: System.TypeInitializationException: The type initializer for 'DnnVsProjectSystem.BuildTools.Tasks.AbstractTask' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
      MSBUILD : Task factory error NMSBT001: 
      MSBUILD : Task factory error NMSBT001:    --- End of inner exception stack trace ---
      MSBUILD : Task factory error NMSBT001:    at DnnVsProjectSystem.BuildTools.Tasks.AbstractTask..cctor()
      MSBUILD : Task factory error NMSBT001:    --- End of inner exception stack trace ---
      MSBUILD : Task factory error NMSBT001:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
      MSBUILD : Task factory error NMSBT001:    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      MSBUILD : Task factory error NMSBT001:    at UtilPack.NuGet.MSBuild.TaskReferenceCreator.CreateTaskReferenceHolder(String taskTypeName, NuGetAssemblyResolver resolver, String packageID, String packageVersion, String assemblyPath, String msbuildFrameworkAssemblyName, ResolverLogger logger)
      MSBUILD : Task factory error NMSBT001:    at UtilPack.NuGet.MSBuild.TaskReferenceCreator.CreateTaskReferenceHolder(String taskTypeName, NuGetAssemblyResolver resolver, String packageID, String packageVersion, String assemblyPath, String msbuildFrameworkAssemblyName, ResolverLogger logger)
      MSBUILD : Task factory error NMSBT001:    at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.CreateExecutionHelper(String taskName, XElement taskBodyElement, String taskPackageID, String taskPackageVersion, String taskAssemblyFullPath, String taskAssemblyPathHint, BoundRestoreCommandUser restorer, ResolverLogger resolverLogger, GetFileItemsDelegate getFiles, String assemblyCopyTargetFolder, AppDomainSetup& appDomainSetup)
      MSBUILD : Task factory error NMSBT001:    at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.<>c__DisplayClass35_5.<Initialize>b__7()
      MSBUILD : Task factory error NMSBT001:    at System.Lazy`1.CreateValue()
      MSBUILD : Task factory error NMSBT001:    at System.Lazy`1.LazyInitValue()
      MSBUILD : Task factory error NMSBT001:    at System.Lazy`1.get_Value()
      MSBUILD : Task factory error NMSBT001:    at UtilPack.ReadOnlyResettableLazy`1.get_Value()
      MSBUILD : Task factory error NMSBT001:    at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.Initialize(String taskName, IDictionary`2 parameterGroup, String taskBody, IBuildEngine taskFactoryLoggingHost)

      C:\Users\darre\.nuget\packages\dnnvsprojectsystem.buildtools\0.0.1-alpha0000\build\functionality\Functionality.targets(90,5): error MSB4175: The task factory "UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory" could not be loaded from the assembly "C:\Users\darre\.nuget\packages\utilpack.nuget.msbuild\2.6.0\build\\net45\UtilPack.NuGet.MSBuild.dll". The type initializer for 'DnnVsProjectSystem.BuildTools.Tasks.AbstractTask' threw an exception.

**Comment by stazz** [comment]
Hi Darrell,

Do you get the same error under dotnet as well? Can you turn on verbosity to see where did it load the task assembly from (thus revealing target framework)? Do you know which desktop .NET version you have currently installed?

On my machine, the desktop framework has version `4.0.0.0` of the `System.Runtime` assembly in `C:\Windows\Microsoft.NET\Framework64\v4.0.30319`, and also in GAC (`C:\Windows\Microsoft.NET\assembly`). Does it try version `4.1.2.0` first because your task is .NET Standard -compiled?

**Comment by stazz** [comment]
The version `2.7.0` now detects .NET Core 2.1 automatically.
