### ISSUE TITLE
Mistakes in SCRAM names

### ISSUE THREAD

**Issue by Neustradamus** [stazz/UtilPack#37]
Dear @stazz,

In first, I wish you a Happy New Year!

Can you change here: https://github.com/stazz/UtilPack/blob/develop/Source/UtilPack.Cryptography.SASL.SCRAM/README.md

1/ "This is library implementing SCRAM-(SHA128|256|512) protocol without dynamically allocating any strings. The SCRAM protocol handlers are accessible via extension methods for BlockDigestAlgorithm interface of UtilPack.Cryptography.Digest project."
by
"This is library implementing SCRAM-(SHA-1|SHA-256|SHA-512) protocol without dynamically allocating any strings. The SCRAM protocol handlers are accessible via extension methods for BlockDigestAlgorithm interface of UtilPack.Cryptography.Digest project."

2/ "// Example of using SCRAM-SHA256"
by
"// Example of using SCRAM-SHA-256"

----------------------------------------------

Here too:
- https://www.nuget.org/packages/UtilPack.Cryptography.SASL.SCRAM/

And in current nuget topics:
"utility cryptography sasl scram sha-128 sha-256 sha-512 digest hash"
by
"utility cryptography sasl scram scram-sha-1 scram-sha-256 scram-sha-512 sha-1 sha-256 sha-512 digest hash"

Thanks in advance.

**Comment by stazz** [comment]
I was able to update the README in repo and NuGet, however, updating NuGet topics seems to be impossible without making a new release.

I'll create separate issue for that and try to dig out my ancient deployment scripts for this, but prepare that it might take a while. This repo was done before I really got into DevOps world and started to automate things like the correct workflows, pipelines, and so on. :)

**Comment by stazz** [comment]
It looks like I actually renamed the `UtilPack.Cryptography.*` packages to `FluentCryptography.*`.

I've created the [follow-up issue in the correct repo](https://github.com/stazz/FluentCryptography/issues/1).
