### ISSUE TITLE
Question - task name

### ISSUE THREAD

**Issue by dazinator** [stazz/UtilPack#4]
Hi again!
In the README - this bit:

> The UsingTask element should have its Condition, TaskFactory and AssemblyFile attributes always the same. By default, the only customizable attribute should be TaskName, which should be the full type name of the task to execute.

Would you mind clarifying the "full type name" bit for me? 

Is this:

1. The assembly qualified, type name? i.e `Foo.Bar.DoStuffTask, Foo`
2. The namespace qualified type name, without assembly qualification? i.e `Foo.Bar.DoStuff`
3. The type name, without namespace or assembly: `DoStuff`

**Comment by stazz** [comment]
Hi @dazinator ,
The full type name is number two: "namespace qualified type name". The assembly within the NuGet package which holds the type can be controlled via AssemblyPath task parameter.

**Comment by dazinator** [comment]
Thanks for clarification
