### ISSUE TITLE
PackageVersion = This Package!

### ISSUE THREAD

**Issue by dazinator** [stazz/UtilPack#5]
I'd like to do the following:

1. In my nugget package, I am including a targets file in the build folder.
2. In that targets file I am including the `PackageReference` for the `UtilPack.NuGet.MSBuild` package.
3. In that same nuget package, I am including my msbuild task that I want to run.
4. In the targets file I am also adding the util pack task factory markup in order to run my task.

So here is the flow I am going for:

1. User adds a package reference to my nuget package
2. My nuget package adds the package reference for utilpack.
3. My nuget package also has my msbuild tasks, and adds the appropriate util pack `using task` elements for them.

Here is my problem.. 

1. I am not sure if adding a package reference, `during a restore` is workable..
2. 

> PackageVersion: This element should contain the version string of the package which contains the task to be executed. If not present, the newest version will be used. Should be version range.

I need this `PackageVersion` to be the version of the package that the current targets are in.

For example if a user adds my nuget package version 1.0.1 - I need this value to be `1.0.1`. If they add `1.0.2` - I need this to be `1.0.2`.

I could hardcode this value in the targets file each time I release I would have to remember to update it so I want to avoid this.. So i'm trying to look for a way to tell the task factory to look in the version of the package reference containing this targets file!

**Comment by dazinator** [comment]
Figured out answer to 1) - It's pretty obvious really - I just need to declare `UtilPack.NuGet.MSBuild` as a dependency in my nuspec file. Just leaves number 2 to solve now.

**Comment by stazz** [comment]
I think there is a way to automate the emission of the version string into your targets file during the release build. I can provide a live example sunday or monday evening - having an extremely busy weekend right now! Basically it involves using MSBuild "WriteLinesTo" (or similar) task to emit a file during build. It would know your version since you are probably using <Version> property in your .csproj.

**Comment by dazinator** [comment]
Oh sounds great - Yeah I typically pass in /p:PackageVersion when building for release.

**Comment by stazz** [comment]
How about this solution: you have a `.tagets.partial` file which has your normal targets file content, except there are some special tokens there, which are  then transformed by build process into actual values, and final result written to `.targets` file.
The `YourPackageID.targets.partial` file content could be something like this, with `£PackageVersion£` token was chosen at random just for example's sake:

```xml
<Project>
  <!-- ... -->
  <UsingTask
    Condition=" '$(UtilPackNuGetMSBuildAssemblyPath)' != '' "
    TaskFactory="UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory"
    AssemblyFile="$(UtilPackNuGetMSBuildAssemblyPath)"
    TaskName="YourTaskNameHere"
  >
    <Task>
      <NuGetTaskInfo>
        <PackageVersion>£PackageVersion£</PackageVersion>
      </NuGetTaskInfo>
    </Task>
  </UsingTask>
</Project>
```

Then, in your release build process, assuming your current package version is hiding behind a property called `PackageVersion`, use this:
```xml
  <PropertyGroup>
    <PathToPartialFile>path/to/YourPackageID.targets.partial</PathToPartialFile>
    <PathToTargetsFile>path/to/YourPackageID.targets</PathToTargetsFile>
    <PartialFileContent>$([System.IO.File]::ReadAllText('$(PathToPartialFile)'))</PartialFileContent>
    <TargetsFileContent>$([System.Text.RegularExpressions.Regex]::Replace( '$(PartialFileContent)', '£PackageVersion£', '$(PackageVersion)' ) )</TargetsFileContent>
  </PropertyGroup>
  
  <ItemGroup>
    <YourPackageIDTargetsFile Include="$(PathToTargetsFile)" />
  </ItemGroup>
  
  <Target
    Name="GenerateTargetsFile"
    BeforeTargets="BeforeBuild"
    Inputs="$(PathToPartialFile)"
    Outputs="@(YourPackageIDTargetsFile)"
    >
    <WriteLinesToFile
      File="$(PathToTargetsFile)"
      Overwrite="true"
      Encoding="UTF-8"
      Lines="$(TargetsFileContent)"
      />
  </Target>
```

How would that work for you?

**Comment by dazinator** [comment]
LGTM! Thank you - I will give this a try!
