### ISSUE TITLE
MSBUILD : Task factory error error NMSBT003: Failed to find suitable assembly in DnnVsProjectSystem.BuildTools@0.0.2-alpha0004.

### ISSUE THREAD

**Issue by dazinator** [stazz/UtilPack#6]
I'm hitting this problem when trying to build a project using the util pack task factory:

```
MSBUILD : Task factory error error NMSBT003: Failed to find suitable assembly in DnnVsProjectSystem.BuildTools@0.0.2-alpha0004.
```

Same error happens for both desktop msbuild and `dotnet build` (2.0.0).

My nuget package folder structure looks like this:

![image](https://user-images.githubusercontent.com/3176632/30512368-cc963ed6-9ae5-11e7-9270-f792be5cee61.png)

I am placing the assemblies inside the build folder i.e build/net461 and build/netcoreapp2.0

My `using task` declaration is in the targets file within my nuget package (the targets file is shown in the image above) and it looks like this:

```

  <UsingTask
    Condition=" '$(UtilPackNuGetMSBuildAssemblyPath)' != '' "
    TaskFactory="UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory"
    AssemblyFile="$(UtilPackNuGetMSBuildAssemblyPath)"
    TaskName="DnnVsProjectSystem.BuildTools.Tasks.FindDnnManifestFile">
    <Task>
      <NuGetTaskInfo>
        <!-- This element is mandatory, and should be the package ID of the package containing MSBuild task to be executed. -->
        <PackageID>DnnVsProjectSystem.BuildTools</PackageID>

        <!-- Optionally specify the version. By default, newest will be used. Note that leaving this out will cause NuGet restore to always scan all sources. -->

        <PackageVersion>0.0.2-alpha0004</PackageVersion>

     </NuGetTaskInfo>
    </Task>
  </UsingTask>

```

What could I be doing wrong?

**Comment by dazinator** [comment]
I have also tried placing the assemblies additionally in the /lib folder in the nugget package (and under the /tools folder too) with the same result. 

It would be good to be able to see the search paths where the task factory has searched for the assembly in the log output - I did try `dotnet build -v Diagnostic` but I couldn't see any more detailed output around this. I tried to delve into the source code for the task factory but to say that it is a bit complicated from an outsiders perspective is an understatement! :-)

**Comment by dazinator** [comment]
Was just looking at the diagnostic output:

```
Initializing task factory "UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory" from assembly "C:\Users\darre\.nuget\packages\utilpack.nuget.msbuild\1.1.2\build\\netcoreapp1.1\UtilPack.NuGet.MSBuild.dll".
                   [NuGet Minimal]: Restoring packages for C:\Users\darre\AppData\Local\Temp\she3rxkl.tnh\dummy...
                   [NuGet Verbose]: Restoring packages for .NETCoreApp,Version=v2.0...
                   [NuGet Verbose]: Resolving conflicts for .NETCoreApp,Version=v2.0...
                   [NuGet Verbose]: Checking compatibility of packages on .NETCoreApp,Version=v2.0.
                   [NuGet Debug]: Checking compatibility for Restoring: (DnnVsProjectSystem.BuildTools, [0.0.2-alpha0004, )) 1.0.0 with .NETCoreApp,Version=v2.0.
                   [NuGet Debug]: Checking compatibility for DnnVsProjectSystem.BuildTools 0.0.2-alpha0004 with .NETCoreApp,Version=v2.0.
                   [NuGet Debug]: Checking compatibility for UtilPack.NuGet.MSBuild 1.1.2 with .NETCoreApp,Version=v2.0.
                   [NuGet Verbose]: All packages and projects are compatible with .NETCoreApp,Version=v2.0.
                   [NuGet Minimal]: Restoring packages for C:\Users\darre\AppData\Local\Temp\she3rxkl.tnh\dummy...
                   [NuGet Verbose]: Restoring packages for .NETCoreApp,Version=v2.0...
                   [NuGet Verbose]: Resolving conflicts for .NETCoreApp,Version=v2.0...
                   [NuGet Verbose]: Checking compatibility of packages on .NETCoreApp,Version=v2.0.
                   [NuGet Debug]: Checking compatibility for Restoring: (Microsoft.NETCore.App, [2.0.0, )) 1.0.0 with .NETCoreApp,Version=v2.0.
                   [NuGet Debug]: Checking compatibility for Microsoft.NETCore.App 2.0.0 with .NETCoreApp,Version=v2.0.
                   [NuGet Debug]: Checking compatibility for Microsoft.NETCore.DotNetHostPolicy 2.0.0 with .NETCoreApp,Version=v2.0.
                   [NuGet Debug]: Checking compatibility for Microsoft.NETCore.Platforms 2.0.0 with .NETCoreApp,Version=v2.0.
                   [NuGet Debug]: Checking compatibility for NETStandard.Library 2.0.0 with .NETCoreApp,Version=v2.0.
                   [NuGet Debug]: Checking compatibility for Microsoft.NETCore.DotNetHostResolver 2.0.0 with .NETCoreApp,Version=v2.0.
                   [NuGet Debug]: Checking compatibility for Microsoft.NETCore.DotNetAppHost 2.0.0 with .NETCoreApp,Version=v2.0.
                   [NuGet Verbose]: All packages and projects are compatible with .NETCoreApp,Version=v2.0.
13:52:53.932     1>MSBUILD : Task factory error error NMSBT003: Failed to find suitable assembly in DnnVsProjectSystem.BuildTools@0.0.2-alpha0004. [C:\Users\darre\Documents\visual studio 2017\Projects\DnnExtension96\DnnExtension96\DnnExtension96.dnnproj]
13:52:53.932     1>C:\Users\darre\.nuget\packages\dnnvsprojectsystem.buildtools\0.0.2-alpha0004\build\DnnVsProjectSystem.BuildTools.targets(193,5): error MSB4036: The "DnnVsProjectSystem.BuildTools.Tasks.FindDnnManifestFile" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\dotnet\sdk\2.0.0" directory. [C:\Users\darre\Documents\visual studio 2017\Projects\DnnExtension96\DnnExtension96\DnnExtension96.dnnproj]
```

This line looked odd to me - but probably just my lack of an understanding:

> Initializing task factory "UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory" from assembly "C:\Users\darre\.nuget\packages\utilpack.nuget.msbuild\1.1.2\build\\netcoreapp1.1\UtilPack.NuGet.MSBuild.dll".

I am building using `dotnet build` and I am using `dotnet --version 2.0.0` - I was just surprised to see that the factory is loaded from netcoreapp1.1 folder rather than netcoreapp2.0 - is that correct?

**Comment by dazinator** [comment]
I have made a fair few changes in attempting to get to the bottom of this. I am including more supported targets in my nugget package now - so it now has binaries for:

- netcoreapp1.0
- netcoreapp2.0
- netstandard1.5
- net461
- net452

I also upgraded my vs2017 preview to the latest preview  - that's a side by side install, and I am using VS2017 stable (not preview) when testing this so hoping that shouldn't impact anything.

I also made sure my task is depending upon msbuild `15.3` packages as I saw your comment about task factories not working with msbuild 15.1. 

If I do `dotnet msbuild /version` from command line it yields: `15.3.409.57025`

When I add my nuget package to a project - it restores the util pack package as a dependency which is good. When I then `dotnet build` that project - my tasks aren't run and I am now seeing this initialisation (missing method exception) error: 

```

MSBUILD : Task factory error error NMSBT003: Exception in initialization: System.MissingMethodException: Method not found: 'NuGet.Commands.RestoreCommandProviders NuGet.Commands.RestoreCommandProviders.Create(System.String, System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<NuGet.Protocol.Core.Types.SourceRepository>, NuGet.Protocol.Core.Types.SourceCacheContext, NuGet.Common.ILogger)'.\r [C:\Users\darre\Documents\Visual Studio 2017\Projects\DnnExtension103\DnnExtension103\DnnExtension103.dnnproj]
MSBUILD : Task factory error error NMSBT003:    at UtilPack.NuGet.BoundRestoreCommandUser..ctor(ISettings nugetSettings, NuGetFramework thisFramework, String runtimeIdentifier, ILogger nugetLogger, SourceCacheContext sourceCacheContext, Boolean leaveSourceCacheOpen)\r [C:\Users\darre\Documents\Visual Studio 2017\Projects\DnnExtension103\DnnExtension103\DnnExtension103.dnnproj]
MSBUILD : Task factory error error NMSBT003:    at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.Initialize(String taskName, IDictionary`2 parameterGroup, String taskBody, IBuildEngine taskFactoryLoggingHost) [C:\Users\darre\Documents\Visual Studio 2017\Projects\DnnExtension103\DnnExtension103\DnnExtension103.dnnproj]
C:\Users\darre\.nuget\packages\dnnvsprojectsystem.buildtools\0.0.2-alpha0007\build\DnnVsProjectSystem.BuildTools.targets(207,5): error MSB4036: The "DnnVsProjectSystem.BuildTools.Tasks.FindDnnManifestFile" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\dotnet\sdk\2.0.2-vspre-006949" directory. [C:\Users\darre\Documents\Visual Studio 2017\Projects\DnnExtension103\DnnExtension103\DnnExtension103.dnnproj]

```

**Comment by stazz** [comment]
> I was just surprised to see that the factory is loaded from netcoreapp1.1 folder rather than netcoreapp2.0 - is that correct?

Yes - the UtilPack.NuGet.MSBuild is compiled against .NET Core App 1.1 - so the folder name comes from that. .NET Core App 2.0 is backward-compatible - meaning it is able to run .NET Core App 1.1 applications  without them needing to explicitly target .NET Core App 2.0.

> MSBUILD : Task factory error error NMSBT003: Failed to find suitable assembly in DnnVsProjectSystem.BuildTools@0.0.2-alpha0004

This happens on line 276 of `Source/UtilPack.NuGet.MSBuild/NuGetTaskRunnerFactory.cs`. It seems that `UtilPackNuGetUtility.GetAssemblyPathFromNuGetAssemblies` method is not able to find the assembly within your NuGet package `build/netcoreapp2.0` folder - are you specifying the AssemblyPath task parameter explicitly? Are there multiple assemblies inside `build/netcoreapp2.0` folder of your NuGet package?

And yes, source code is quite complex. :) Big reason is that I have to play inventively and carefully with AppDomains in .NET Desktop environment - .NET Core is much easier with its AssemblyLoadContext.

> I am now seeing this initialisation (missing method exception) error:

As for MissingMethodError - it seems Microsoft has once again made breaking change in NuGet library. The UtilPack.NuGet.MSBuild is compiled against NuGet 4.3.0 - I also got similar errors when I was compiling against NuGet 4.0.0 and people tried to use the task factory in 15.3 environment. When you run `dotnet msbuild` command, the NuGet assemblies are loaded within your dotnet installation, and are considered "trusted assemblies", and thus my task factory never gets to load the version of NuGet assemblies it was compiled against, even though they are supplied in the same folder with `UtilPack.NuGet.MSBuild.dll`.

**Comment by dazinator** [comment]
> are you specifying the AssemblyPath task parameter explicitly? 

I have tried specifying this explicitly and omitting it, with the same problem.

> Are there multiple assemblies inside build/netcoreapp2.0 folder of your NuGet package

Yes - because I am using  `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` in my csproj file, so that all dependencies are output to the build folder - I then include them all in the nugget package.

> and thus my task factory never gets to load the version of NuGet assemblies it was compiled against, even though they are supplied in the same folder with UtilPack.NuGet.MSBuild.dll.

Sounds nasty. So do you have to use reflection to find / invoke the existing types to try and be compatible with all of the versions?

**Comment by dazinator** [comment]
I will create a repro

**Comment by dazinator** [comment]
I have added a repro in a branch here: https://github.com/dazinator/UtilPack/tree/issue-6

1. Open the solution.
2. Pack the `Repro.Tasks` project - this will output the nuget package in $SolutionDir\local-packages
3. Build the `Repro.TestProject` - this should produce the error.

**Comment by stazz** [comment]
I finally managed to reproduce and track the cause of this issue. The `UtilPackNuGetUtility.GetAssemblyPathFromNuGetAssemblies` had faulty algorithm for looking up assembly from a set of potential assemblies, given assembly path hint. I have fixed the algorithm for UtilPack.NuGet.MSBuild verson 1.1.3, and will release other fixed UtilPack.NuGet.* packages later.

I also fixed the documentation so better reflect the fact that the `AssemblyPath` is resolved not from within package home directory, but the current target framework directory (e.g. `lib/net45`). In your case, `AssemblyPath` would be just `DnnVsProjectSystem.BuildTools.dll`.

May I ask, out of curiosity, what are the reasons behind setting the `CopyLocalLockFileAssemblies` to `true`? As long as you are only using SDK assemblies, or assemblies from other NuGet packages, UtilPack.NuGet.MSBuild task factory will take care of restoring packages and loading them for your task when your task runs.

**Comment by dazinator** [comment]
Nice one - I look.forward to trying the fixed version!

Reason for including all assemblies was mainly because it was necessary before I found utilpack! For UtilPack to load my dependencies from other nuget packages, I assume I just need to list my dependencies in my nuspec is that right?  I will look at moving to listing these as dependencies in my nuspec instead then.. my only hestitation - I need to make sure that my dependencies arent passed onto the consuming project as dependencies..

If a consumer adds just utilpack nuget package to their project, and manually adds the task factory markup pointing to a tool - utilpack can restore the tool in a way that isolates its dependencies from the project ( because the tool is not itself installed into the project). However - the shortcut approach im using is that consumers add my tools package directly - which brings in utilpack. The project will therefore see my tools dependencies in its nuspec unless I can exclude them perhaps by nuspec directives.  For tools packages it has been a standard practice to place the tool under the /tools folder as a self contained exe / all assemblies etc so that it can be executed in isolation. So yeah.. - I just need to ensure my tool is kept completely self contained!

I could split my tool into two nuget packages. The first adds utilpack and the tsdkfactory targets pointing to the second nuget package - which would be my actual tool that utilpack would restore and thus be isolared. I think this would be more in keeping with the approach you have documented perhaps, but its more maintainence on my part. I will see how I get on!

**Comment by stazz** [comment]
Hi @dazinator , just making sure, did 1.1.3 version fix this for you? :)

Regarding this question:
> For UtilPack to load my dependencies from other nuget packages, I assume I just need to list my dependencies in my nuspec is that right?

Yes, that should be enough. If it isn't, then you have found another bug in UtilPack.NuGet.MSBuild task factory!

As for the redistribution problems - I'll create separate issue for that. 👍
