### ISSUE TITLE
Handle ITask property

### ISSUE THREAD

**Issue by dazinator** [stazz/UtilPack#9]
build task with an output property like so:

```
        [Output]
        public ITaskItem DefaultManifestFileItemForPackage { get; set; }

```

Causes the utilpack msbuild task factory to raise an invalid cast exception. 

Changing it to an array is the workaround.

**Comment by stazz** [comment]
Ah, I see it in the code now - it seems that I haven't prepared for non-array `ITaskItem`s at all. Maybe at some point MSBuild didn't like `ITaskItem` properties unless they were array-like... Or maybe I didn't think anyone wanted non-array `ITaskItem`.

In any case, I'll fix this.
